vvp/urls.py
from django.urls import path
from . import views
app_name = 'vvp'
urlpatterns = [
    path('',views.index,name='index'),
    path('alumni/',views.alumni_view,name='alumni'),
    path('our-gems/',views.our_gems_view,name='gems'),
    path('our-gems/add/',views.gems_form,name='gems_form'),
    path('gallery/',views.gallery_view,name='gallery'),
    path('gallery/add/',views.gallery_form,name='gallery_form'),
    path('notices-events/',views.notice,name='notice'),
    path('notices-events/add/',views.notice_form,name='notice_form'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('staff/',views.staffmembers,name='staff'),
    path('committee',views.committeemembers,name='committee'),
]

vvpeeth/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('vvp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vvp/models.py
from django.db import models
# Create your models here.
class alumni(models.Model):

    First_name = models.CharField(max_length=50)
    Last_name = models.CharField(max_length=50)
    Email = models.EmailField(max_length=50)
    Phone = models.CharField(max_length=15)
    Batch = models.CharField(max_length=5)
    Photo = models.FileField(upload_to='alumni/',blank=True,null=True)
    address = models.CharField(max_length=100)
    date_time = models.CharField(max_length=100)
    current_employment_status = models.CharField(max_length=1000)

    def __str__(self):
        return self.First_name + ' ' + self.Last_name

CHOICES = (
    ('10th','10th'),
    ('12th','12th'),
)
class our_gems(models.Model):

    Name = models.CharField(max_length=50)
    Marks = models.CharField(max_length=20)
    Photo = models.FileField(upload_to='our_gems/')
    Batch = models.CharField(max_length=5)
    Class = models.CharField(max_length=10,choices = CHOICES)

    def __str__(self):
        return self.Name


class gallery(models.Model):

    Photo = models.FileField(upload_to='gallery/')
    Title = models.CharField(max_length=20)
    Description = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Title

class notice_events(models.Model):

    date = models.DateTimeField(auto_now_add=True)
    Photo = models.ImageField(upload_to='n_e/img')
    File = models.FileField(upload_to='n_e/docs',null=True,blank=True)
    Title = models.CharField(max_length=30)
    Description = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Title +' '+ str(self.date)


class staff(models.Model):

    s_no = models.IntegerField(default=0)
    name = models.CharField(max_length=50)
    Designation = models.CharField(max_length=100)
    Qualification = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class committee(models.Model):

    s_no = models.IntegerField(default=0)
    name = models.CharField(max_length=50)
    Designation = models.CharField(max_length=100)

    def __str__(self):
        return self.name

vvp/views.py
from django.shortcuts import render,redirect
from .models import alumni,gallery,notice_events,staff,committee,our_gems
from django.utils import timezone
from django.contrib.auth.models import auth
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    obj_gallery = gallery.objects.all().order_by('date').reverse()[:6]
    obj_notice = notice_events.objects.all().order_by('date').reverse()[:4]
    return render(request,'home.html',{'gallery':obj_gallery,'notice':obj_notice})

def alumni_view(request):
    if request.method=='POST':
        obj = alumni()
        obj.First_name = request.POST['fname']
        obj.Last_name = request.POST['lname']
        obj.Email = request.POST['email']
        obj.Phone = request.POST['phone']
        obj.Batch = request.POST['batch']
        try :
             obj.Photo = request.FILES['photo']
        except:
            pass
        obj.address = request.POST['add1'] + ' ' + request.POST['add2'] + ' ' + request.POST['city'] + ' ' + request.POST['state'] + ' ' + request.POST['zipcode']
        obj.date_time = timezone.now()
        obj.current_employment_status = request.POST['current']
        obj.save()
        return redirect('/')
    return render(request,'alumni.html')

def our_gems_view(request):
    obj_tenth = reversed(our_gems.objects.filter(Class='10th').order_by('Batch','Marks'))
    obj_twelth = reversed(our_gems.objects.filter(Class='12th').order_by('Batch','Marks'))
    return render(request,'our-gems.html',{'tenth':obj_tenth,'twelth':obj_twelth})

@login_required
def gems_form(request):
    if request.method=='POST':
        obj = our_gems()
        obj.Name = request.POST['name']
        obj.Marks = request.POST['marks']
        obj.Photo = request.FILES['photo']
        obj.Batch = request.POST['batch']
        obj.Class = request.POST['class']
        obj.save()
        return render(request,'our_gems_form.html',{'msg':'Entry Added Successfully!'})
    return render(request,'our_gems_form.html')


def staffmembers(request):
    obj = staff.objects.all().order_by('s_no')
    return render(request,'staff-members.html',{'item':obj})

def committeemembers(request):
    obj = committee.objects.all().order_by('s_no')
    return render(request,'committee-members.html',{'item':obj})

def gallery_view(request):
    obj = reversed(gallery.objects.all().order_by('date'))
    return render(request,'gallery.html',{'item':obj})

@login_required
def gallery_form(request):
    if request.method=='POST':
        obj = gallery()
        obj.Photo = request.FILES['photo']
        obj.Title = request.POST['title']
        obj.Description = request.POST['Description']
        obj.save()
        return render(request,'gallery_form.html',{'msg':'Photo Added Successfully!'})
    return render(request,'gallery_form.html')

def notice(request):
    obj = reversed(notice_events.objects.all().order_by('date'))
    return render(request,'notice.html',{'item':obj})

@login_required
def notice_form(request):
    if request.method=='POST':
        obj = notice_events()
        obj.Photo = request.FILES['photo']
        try:
            obj.File = request.FILES['file']
        except:
            pass
        obj.Title = request.POST['title']
        obj.Description = request.POST['Description']
        obj.save()
        return render(request,'notice_form.html',{'msg':'Entry Added Successfully!'})
    return render(request,'notice_form.html')

def login(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username = username, password = password)
        if user != None:
            auth.login(request,user)
            return redirect('/')
        else:
            dict = {'msg': 'Invalid Credentials'}
            return render(request,'login.html',dict)
    return render(request,'login.html')

def logout_view(request):
    logout(request)
    return render(request,'login.html',{'msg':'Logged Out Successfully!'})

vvp/templates/alumni.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Alumni Detail Form {% endblock %}
{% block content %}
<!-- =======ALUMNI FORM======== -->
<div class="alumni-form">
  <div class="container">
    <div class="heading">
    <center>
      <h1>ALUMNI FORM</h1>
      <p>To stay connected to your school by receiving regular update about activities in school please fill the given form.</p>
      <hr class="heading-underline">
      </center>
    </div>
    <form class="alumni-form-container" method='POST' enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-6 ">
          <label for="first-name">First Name</label>
          <input type="text" class="form-control" id="first-name" name='fname' placeholder="First Name" required>
        </div>
        <div class="form-group col-md-6">
          <label for="last-name">Last Name</label>
          <input type="text" class="form-control" id="last-name" name='lname' placeholder="Last Name" required>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6 ">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="email" name='email' placeholder="Email" required>
        </div>
        <div class="form-group col-md-6">
          <label for="phone">Contact</label>
          <input type="text" class="form-control" id="phone" name='phone' placeholder="Phone Number" required>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6 ">
          <label for="batch">Batch</label>
          <input type="text" class="form-control" id="batch" name='batch' placeholder="Batch Year" required>
        </div>
        <div class="form-group col-md-6 photo">
          <label for="photo">Photo</label>
          <input type="file" class="form-control" id="photo" name='photo' placeholder="Upload photo" >
        </div>
      </div>


      <div class="form-group">
        <label for="inputAddress">Address</label>
        <input type="text" class="form-control" id="inputAddress" name='add1' placeholder="1234 Main St" required>
      </div>
      <div class="form-group">
        <label for="inputAddress2">Address 2</label>
        <input type="text" class="form-control" id="inputAddress2" name='add2' placeholder="Apartment, studio, or floor" required>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">City</label>
          <input type="text" class="form-control" name='city' id="inputCity" required>
        </div>
        <div class="form-group col-md-4">
          <label for="inputState">State</label>
          <select id="inputState" class="form-control" name='state' required>
            <option selected>Choose...</option>
            <option value="Andhra Pradesh">Andhra Pradesh</option>
            <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
            <option value="Arunachal Pradesh">Arunachal Pradesh</option>
            <option value="Assam">Assam</option>
            <option value="Bihar">Bihar</option>
            <option value="Chandigarh">Chandigarh</option>
            <option value="Chhattisgarh">Chhattisgarh</option>
            <option value="Dadar and Nagar Haveli">Dadar and Nagar Haveli</option>
            <option value="Daman and Diu">Daman and Diu</option>
            <option value="Delhi">Delhi</option>
            <option value="Lakshadweep">Lakshadweep</option>
            <option value="Puducherry">Puducherry</option>
            <option value="Goa">Goa</option>
            <option value="Gujarat">Gujarat</option>
            <option value="Haryana">Haryana</option>
            <option value="Himachal Pradesh">Himachal Pradesh</option>
            <option value="Jammu and Kashmir">Jammu and Kashmir</option>
            <option value="Jharkhand">Jharkhand</option>
            <option value="Karnataka">Karnataka</option>
            <option value="Kerala">Kerala</option>
            <option value="Madhya Pradesh">Madhya Pradesh</option>
            <option value="Maharashtra">Maharashtra</option>
            <option value="Manipur">Manipur</option>
            <option value="Meghalaya">Meghalaya</option>
            <option value="Mizoram">Mizoram</option>
            <option value="Nagaland">Nagaland</option>
            <option value="Odisha">Odisha</option>
            <option value="Punjab">Punjab</option>
            <option value="Rajasthan">Rajasthan</option>
            <option value="Sikkim">Sikkim</option>
            <option value="Tamil Nadu">Tamil Nadu</option>
            <option value="Telangana">Telangana</option>
            <option value="Tripura">Tripura</option>
            <option value="Uttar Pradesh">Uttar Pradesh</option>
            <option value="Uttarakhand">Uttarakhand</option>
            <option value="West Bengal">West Bengal</option>
          </select>
        </div>
        <div class="form-group col-md-2">
          <label for="inputZip">Zip</label>
          <input type="text" class="form-control" name='zipcode' pattern="[0-9]{6}" id="inputZip" required>
        </div>
      </div>
      <div class="form-group">
        <label for="current">Current Employment Status</label>
        <input type="text" class="form-control" id="current" name='current' placeholder="Job/Business Details" required>
      </div>
      <div class="form-group">
        <button type="submit" class="submit-btn" name="button">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

vvp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href='{% static "css/home.css" %}'>
    <link rel="stylesheet" href='{% static "css/nav&footer.css" %}'>
    <link rel="stylesheet" href='{% static "css/gallery.css" %}'>
    <link rel="stylesheet" href='{% static "css/alumni.css" %}'>
    <link rel="stylesheet" href='{% static "css/all.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/fontawesome.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/lightbox.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/login.css" %}'>
    <link rel="stylesheet" href='{% static "css/our-gems.css" %}'>
    <link rel="stylesheet" href='{% static "css/table.css" %}'>
    <link rel='icon' href='{% static "img/logo 2.png" %}' type='image/x-icon'>




    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body data-spy="scroll" data-target="#navbarResponsive">
<!-- navigation -->
    <nav class="navbar navbar-expand-lg fixed-top ">
    <div class="container-fluid">
      <a class="navbar-brand mybrand" href='{% url "vvp:index" %}' ><img src='{% static "img/logo 2.png" %}' alt="">vivekanand Vidyapeeth</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
		      <span class="custom-toggler-icon"><i class="fas fa-bars"></i></span>
	    </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
    		<ul class="navbar-nav ml-auto">
    			<li class="nav-item">
    				<a class="nav-link mylink" href='{% url "vvp:gems" %}'>Our Gems</a>
    			</li>
    			<li class="nav-item">
    				<a class="nav-link mylink" href='{% url "vvp:gallery" %}'>Gallery</a>
    			</li>
    			<li class="nav-item">
    				<a class="nav-link mylink" href='{% url "vvp:notice" %}'>Notices and Events</a>
    			</li>
    			<li class="nav-item">
    				<a class="nav-link mylink" href='{% url "vvp:alumni" %}'>Alumni</a>
    			</li>
    			<li class="nav-item">
    				<a class="nav-link mylink" href='{% url "vvp:staff" %}'>Staff Members</a>
    			</li>
    			<li class="nav-item">
    				<a class="nav-link mylink" href='{% url "vvp:committee" %}'>Committee Members</a>
    			</li>
    			<li class="nav-item">
    				<a class="nav-link mylink" href="#contactus">Contact us</a>
    			</li>
    		</ul>
    	</div>

    </div>
    </nav>

{% block content %}
{% endblock %}

<!-- ===================Footer================== -->

<footer class="footer" id='contactus'>
  
<div class="container footer-container">
  <div class="row">
    <div class="col-sm-12 col-md-4">
          <div class="widget dark">
            <img  alt="" src='{% static "img/logo 2.png" %}' width="60px">
            <p id="address">Vivekananda Vidyapeeth EM HSS, Sector-2, Bhilai Nagar - 490001 (C.G.) India</p>
            <ul class="list-inline mt-5">
              <li > <i class="fas fa-phone text-theme-colored2 fa-flip-horizontal mr-5" ></i> <a class="text-gray" href="tel:+91-7999584913">+91-7999584913</a> </li>
		          <li> <i class="fas fa-phone text-theme-colored2 fa-flip-horizontal mr-5" ></i> <a class="text-gray" href="tel:07882226396">0788-2226396</a> </li>
              <li> <i class="fas fa-envelope text-theme-colored2 mr-5"></i> <a class="text-gray" href="mailto:vvpeethbhil@gmail.com">vvpeethbhil@gmail.com</a> </li>
              <!-- <li > <i class="fas fa-globe text-theme-colored2 mr-5"></i> <a class="text-gray" href="#">www.rungtainternational.org</a> </li> -->
            </ul>
            <!-- <ul class="styled-icons icon-sm icon-bordered icon-circled clearfix mt-10 social">
              <li><a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a></li>
              <li><a href="https://twitter.com/" ><i class="fab fa-twitter"></i></a></li>
              <li><a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a></li>
			  <li><a href="https://www.linkedin.com/"><i class="fab fa-linkedin"></i></a></li>
            </ul> -->
          </div>
        </div>

        <div class="col-sm-12 col-md-4">
                  <div class="widget dark">
                    <h4 class="widget-title">Useful Links</h4>
                    <hr class="widget-title-underline">
                    <ul class="angle-double-right list-border">
        			        <li><a href='{% url "vvp:notice" %}'>Latest News</a></li>
                      <li><a href="https://cgbse.nic.in/">CGBSE</a></li>
                      <li><a href="#">Careers</a></li>
                      <li><a href='{% url "vvp:alumni" %}'>Alumni</a></li>
        			        <li><a href='{% url "vvp:notice" %}'>Latest Events</a></li>
                      {% if user.is_authenticated %}
                      <li><a href='{% url "vvp:logout" %}'>Logout</a></li>
                      {% else %}
                      <li><a href='{% url "vvp:login" %}'>Staff Login</a></li>
                      {% endif %}
                    </ul>
                  </div>
                </div>
                <div class="col-sm-12 col-md-4">
                  <div class="widget dark">
                    <h4 class="widget-title">School Timing</h4>
                    <hr class="widget-title-underline">
                    <div class="opening-hours">
                      <ul class="list-border">
                        <li class="clearfix"> <span> Mon - Fri : 9.00 am - 3.00 pm </span>
                          <!-- <div class="value pull-right"> 9.00 am - 3.00 pm </div> -->
                        </li>

                        <li class="clearfix"> <span> Sat :  9.00 am - 1.00 pm </span>
                          <!-- <div class="value pull-right"> 9.00 am - 1.00 pm </div> -->
                        </li>
                        <li class="clearfix"> <span> Sun : Closed  </span>
                          <!-- <div class="value pull-right bg-theme-colored2 text-white closed"> Closed </div> -->
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
  </div>


</div>

</footer>
<div class="footer-bottom">
  <p>Copyright ©2020 | Vivekanand Vidyapeeth | Sector - 2 , Bhilai | All Rights Reserved</p>
</div>



   <!-- =============javascript============= -->
<script src='{% static "js/custom.js" %}' charset="utf-8"></script>
<script src='{% static "js/lightbox-plus-jquery.min.js" %}' charset="utf-8"></script>
<script src='{% static "js/lightbox.js" %}' charset="utf-8"></script>
<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
   AOS.init();
</script>

  </body>
</html>

vvp/templates/committee-members.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Committee Members {% endblock %}
{% block content %}
<!-- =======STAFF-MEMBERS======== -->
<div class="staff-container">
  <div class="container">
    <div class="container-heading">
      <center>
        <h1>Committee members</h1>
        <hr class="heading-underline">
      </center>
    </div>
    <div class="table-staff">
      <table class="table">
     <thead class="thead">
    <tr>
      <th scope="col">S.NO</th>
      <th scope="col">Designation</th>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    {% for item in item %}
    <tr>
      <th scope="row">{{item.s_no}}</th>
      <td>{{item.Designation}}</td>
      <td>{{item.name}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>



    </div>
  </div>
</div>

{% endblock %}

vvp/templates/gallery.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Gallery {% endblock %}
{% block content %}

<!-- =======GALLERY======== -->
<div class="gallery-sec" style="background-image:none; margin-top:7rem;">
  <div class="container">
    {% if user.is_authenticated %}
    <div class="row">
      <div class="add-btn" style="text-align:center; margin:0 auto;">
        <a href="{% url 'vvp:gallery_form' %}"><button type="button" class="login-btn" name="button">Add Photo</button></a>
      </div>


    </div>
    {% endif %}
    <div class="row">
      <div class="col-md-12">
        <div class="header-img text-center">
          <h1 style="color:#142850; font-size: 3rem; text-transform: uppercase; font-weight:600;">Gallery</h1>
          <hr class="title-underline" style="border: .2rem solid rgba(20, 40, 80, 1);">
        </div>

      </div>

    </div>
    <div class="row gallerys">
      {% for item in item %}
      <div class="col-md-6 col-lg-4">
        <div class="single-album">
          <div class="album-img">
            <a href='{{ item.Photo.url}}' data-lightbox="gal">
              <img src='{{ item.Photo.url}}' alt="" height="250px" width="350px">
            </a>

          </div>

        <div class="album-content">
          <div class="album-info">
            <h3>{{item.Title}}</h3>
          </div>
          <p>{{item.Description}}</p>
        </div>
      </div>

    </div>
    {% endfor %}
  </div>
</div>
</div>
{% endblock %}

vvp/templates/notice.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Notices & Events {% endblock %}
{% block content %}

<div class="gallery-sec" style="background-image:none; margin-top:7rem;">
  <div class="container">
    {% if user.is_authenticated %}
    <div class="row" >
      <div class="add-btn" style="text-align:center; margin:0 auto;">
        <a href="{% url 'vvp:notice_form' %}"><button type="button" style="margin: 0 auto;" class="login-btn" name="button">Add Entry</button></a>
      </div>
    </div>
    {% endif %}
    <div class="row">
      <div class="col-md-12">
        <div class="header-img text-center">
          <h1 style="color:#142850; font-size: 3rem; text-transform: uppercase; font-weight:600;">Notices and Events</h1>
          <hr class="title-underline" style="border: .2rem solid rgba(20, 40, 80, 1);">
        </div>

      </div>

    </div>
    <div class="row gallerys">
      {% for item in item %}
      <div class="col-md-6">
        <div class="news-events left-news-event">
          <div class="news-events-img">
            <img src="{{item.Photo.url}}" alt="">
          </div>
          <div class="news-events-info">
            <div class="news-events-date">
              <span>{{item.date|date:'l'}}</span>
              <span>{{item.date|date}}</span>
            </div>
            <h1 class="news-events-title">{{item.Title|truncatechars:10}}</h1>
            <p class="news-events-text">{{item.Description|truncatechars:15}}</p>
            <a href="#" class="news-event-read_more" data-toggle="modal" data-target="#popup{{forloop.counter}}">Read more </a>
          </div>
        </div>
      </div>

  <!-- =================popup================= -->
  <!-- Modal 1 -->
  <div class="modal fade" id="popup{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header" style=" margin-left: 20px;">
          <h1 class="modal-title news-events-title" id="exampleModalLongTitle">{{item.Title}}</h1>
          <div class="news-events-date " style="margin-left: 8rem;">
            <span>{{item.date|date:'l'}}</span>
            <span>{{item.date|date}}</span>
          </div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <center>
            <img src="{{item.Photo.url}}" style="width:90%; margin: 10px; border-radius: 10px;" alt="">
          </center>
          <p class="about__para" style="margin: 10px;">{{item.Description}}</p>
        </div>

        <div class="modal-footer">
      {% if item.File %}
      <a href="{{item.File.url}}" class="news-event-read_more " style="margin: 0 auto;" download>Download PDF</a>
      {% endif %}
      </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
</div>
</div>

{% endblock %}

vvp/templates/our-gems.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Our Gems {% endblock %}
{% block content %}
  <!-- end navigation -->
  <div class="topper-cover">
    <img src='{% static "img/topper-cover.jpg" %}' alt="">
  </div>
<div class="container gems-container">
  {% if user.is_authenticated %}
  <div class="row">
    <div class="add-btn" style="text-align:center; margin:0 auto;">
      <a href="{% url 'vvp:gems_form' %}"><button type="button" class="login-btn" name="button">Add Entry</button></a>
    </div>
  </div>
  {% endif %}
  <div class="class-title">
    <center>
      <h1>Class 10th Achievers</h1>

      </center>
<hr class="underline">
  </div>
  <div class="toppers">
  <div class="row">
    {% for item in tenth %}
    <div class="col-lg-3 col-6 ">
      <div class="card" style="width: 18rem; height:28rem;">
      <img class="card-img-top" src='{{item.Photo.url}}' height="200px" width="160px" alt="Card image cap">
      <div class="card-body">
        <center>
          <h5 class="Name">{{item.Name}}</h5>
          <h5 class="Percentage">{{item.Marks}}</h5>
          <h5 class="Percentage">{{item.Batch}}</h5>
        </center>
      </div>
    </div>
   </div>
   {% endfor %}
  </div>
  </div>

  <div class="class-title">
    <center>
      <h1>Class 12th Achievers</h1>

      </center>
    <hr class="underline">
  </div>
  <div class="toppers">
  <div class="row">
    {% for item in twelth %}
    <div class="col-lg-3 col-6">
      <div class="card" style="width: 18rem; height:28rem;">
      <img class="card-img-top" src='{{item.Photo.url}}' alt="Card image cap">
      <div class="card-body">
        <center>
          <h5 class="Name">{{item.Name}}</h5>
          <h5 class="Percentage">{{item.Marks}}</h5>
        </center>
      </div>
      </div>
    </div>
    {% endfor %}
  </div>
  </div>


</div>
{% endblock %}